#!/bin/sh
env GTK_IM_MODULE=fcitx QT_IM_MODULE=fcitx XMODIFIERS=@im=fcitx QT_QPA_PLATFORMTHEME=qt5ct \
        MOZ_WEBRENDER=1 MOZ_X11_EGL=1 MOZ_ENABLE_WAYLAND=1 \
        SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/ssh-agent.socket XDG_CURRENT_DESKTOP=sway LIBSEAT_BACKEND=logind \
        _JAVA_AWT_WM_NONREPARENTING=1 WINIT_UNIX_BACKEND=x11 QT_QPA_PLATFORM=wayland SDL_VIDEODRIVER=wayland CLUTTER_BACKEND=wayland dbus-run-session sway
